const REFRESH = 'REFRESH'
const REMOVE_CANINE = 'REMOVE_CANINE'
const CREATE_CANINE = 'CREATE_CANINE'
const LOGIN_REQUEST = 'LOGIN_REQUEST'
const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

module.exports = {
  REFRESH,
  REMOVE_CANINE,
  CREATE_CANINE,
  LOGIN_REQUEST,
  LOGIN_SUCCESS
}
